# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/fullread

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/fullread

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/fullread/CMakeFiles /root/fullread/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/fullread/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named storagenodes

# Build rule for target.
storagenodes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 storagenodes
.PHONY : storagenodes

# fast build rule for target.
storagenodes/fast:
	$(MAKE) -f CMakeFiles/storagenodes.dir/build.make CMakeFiles/storagenodes.dir/build
.PHONY : storagenodes/fast

#=============================================================================
# Target rules for targets named pswitch

# Build rule for target.
pswitch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pswitch
.PHONY : pswitch

# fast build rule for target.
pswitch/fast:
	$(MAKE) -f CMakeFiles/pswitch.dir/build.make CMakeFiles/pswitch.dir/build
.PHONY : pswitch/fast

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

src/client/client_main.o: src/client/client_main.c.o

.PHONY : src/client/client_main.o

# target to build an object file
src/client/client_main.c.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_main.c.o
.PHONY : src/client/client_main.c.o

src/client/client_main.i: src/client/client_main.c.i

.PHONY : src/client/client_main.i

# target to preprocess a source file
src/client/client_main.c.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_main.c.i
.PHONY : src/client/client_main.c.i

src/client/client_main.s: src/client/client_main.c.s

.PHONY : src/client/client_main.s

# target to generate assembly for a file
src/client/client_main.c.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client_main.c.s
.PHONY : src/client/client_main.c.s

src/pswitch/pswitch_main.o: src/pswitch/pswitch_main.c.o

.PHONY : src/pswitch/pswitch_main.o

# target to build an object file
src/pswitch/pswitch_main.c.o:
	$(MAKE) -f CMakeFiles/pswitch.dir/build.make CMakeFiles/pswitch.dir/src/pswitch/pswitch_main.c.o
.PHONY : src/pswitch/pswitch_main.c.o

src/pswitch/pswitch_main.i: src/pswitch/pswitch_main.c.i

.PHONY : src/pswitch/pswitch_main.i

# target to preprocess a source file
src/pswitch/pswitch_main.c.i:
	$(MAKE) -f CMakeFiles/pswitch.dir/build.make CMakeFiles/pswitch.dir/src/pswitch/pswitch_main.c.i
.PHONY : src/pswitch/pswitch_main.c.i

src/pswitch/pswitch_main.s: src/pswitch/pswitch_main.c.s

.PHONY : src/pswitch/pswitch_main.s

# target to generate assembly for a file
src/pswitch/pswitch_main.c.s:
	$(MAKE) -f CMakeFiles/pswitch.dir/build.make CMakeFiles/pswitch.dir/src/pswitch/pswitch_main.c.s
.PHONY : src/pswitch/pswitch_main.c.s

src/share_func/bandwidth.o: src/share_func/bandwidth.c.o

.PHONY : src/share_func/bandwidth.o

# target to build an object file
src/share_func/bandwidth.c.o:
	$(MAKE) -f CMakeFiles/storagenodes.dir/build.make CMakeFiles/storagenodes.dir/src/share_func/bandwidth.c.o
	$(MAKE) -f CMakeFiles/pswitch.dir/build.make CMakeFiles/pswitch.dir/src/share_func/bandwidth.c.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/share_func/bandwidth.c.o
.PHONY : src/share_func/bandwidth.c.o

src/share_func/bandwidth.i: src/share_func/bandwidth.c.i

.PHONY : src/share_func/bandwidth.i

# target to preprocess a source file
src/share_func/bandwidth.c.i:
	$(MAKE) -f CMakeFiles/storagenodes.dir/build.make CMakeFiles/storagenodes.dir/src/share_func/bandwidth.c.i
	$(MAKE) -f CMakeFiles/pswitch.dir/build.make CMakeFiles/pswitch.dir/src/share_func/bandwidth.c.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/share_func/bandwidth.c.i
.PHONY : src/share_func/bandwidth.c.i

src/share_func/bandwidth.s: src/share_func/bandwidth.c.s

.PHONY : src/share_func/bandwidth.s

# target to generate assembly for a file
src/share_func/bandwidth.c.s:
	$(MAKE) -f CMakeFiles/storagenodes.dir/build.make CMakeFiles/storagenodes.dir/src/share_func/bandwidth.c.s
	$(MAKE) -f CMakeFiles/pswitch.dir/build.make CMakeFiles/pswitch.dir/src/share_func/bandwidth.c.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/share_func/bandwidth.c.s
.PHONY : src/share_func/bandwidth.c.s

src/share_func/file_opt.o: src/share_func/file_opt.c.o

.PHONY : src/share_func/file_opt.o

# target to build an object file
src/share_func/file_opt.c.o:
	$(MAKE) -f CMakeFiles/storagenodes.dir/build.make CMakeFiles/storagenodes.dir/src/share_func/file_opt.c.o
	$(MAKE) -f CMakeFiles/pswitch.dir/build.make CMakeFiles/pswitch.dir/src/share_func/file_opt.c.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/share_func/file_opt.c.o
.PHONY : src/share_func/file_opt.c.o

src/share_func/file_opt.i: src/share_func/file_opt.c.i

.PHONY : src/share_func/file_opt.i

# target to preprocess a source file
src/share_func/file_opt.c.i:
	$(MAKE) -f CMakeFiles/storagenodes.dir/build.make CMakeFiles/storagenodes.dir/src/share_func/file_opt.c.i
	$(MAKE) -f CMakeFiles/pswitch.dir/build.make CMakeFiles/pswitch.dir/src/share_func/file_opt.c.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/share_func/file_opt.c.i
.PHONY : src/share_func/file_opt.c.i

src/share_func/file_opt.s: src/share_func/file_opt.c.s

.PHONY : src/share_func/file_opt.s

# target to generate assembly for a file
src/share_func/file_opt.c.s:
	$(MAKE) -f CMakeFiles/storagenodes.dir/build.make CMakeFiles/storagenodes.dir/src/share_func/file_opt.c.s
	$(MAKE) -f CMakeFiles/pswitch.dir/build.make CMakeFiles/pswitch.dir/src/share_func/file_opt.c.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/share_func/file_opt.c.s
.PHONY : src/share_func/file_opt.c.s

src/share_func/network_transfer.o: src/share_func/network_transfer.c.o

.PHONY : src/share_func/network_transfer.o

# target to build an object file
src/share_func/network_transfer.c.o:
	$(MAKE) -f CMakeFiles/storagenodes.dir/build.make CMakeFiles/storagenodes.dir/src/share_func/network_transfer.c.o
	$(MAKE) -f CMakeFiles/pswitch.dir/build.make CMakeFiles/pswitch.dir/src/share_func/network_transfer.c.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/share_func/network_transfer.c.o
.PHONY : src/share_func/network_transfer.c.o

src/share_func/network_transfer.i: src/share_func/network_transfer.c.i

.PHONY : src/share_func/network_transfer.i

# target to preprocess a source file
src/share_func/network_transfer.c.i:
	$(MAKE) -f CMakeFiles/storagenodes.dir/build.make CMakeFiles/storagenodes.dir/src/share_func/network_transfer.c.i
	$(MAKE) -f CMakeFiles/pswitch.dir/build.make CMakeFiles/pswitch.dir/src/share_func/network_transfer.c.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/share_func/network_transfer.c.i
.PHONY : src/share_func/network_transfer.c.i

src/share_func/network_transfer.s: src/share_func/network_transfer.c.s

.PHONY : src/share_func/network_transfer.s

# target to generate assembly for a file
src/share_func/network_transfer.c.s:
	$(MAKE) -f CMakeFiles/storagenodes.dir/build.make CMakeFiles/storagenodes.dir/src/share_func/network_transfer.c.s
	$(MAKE) -f CMakeFiles/pswitch.dir/build.make CMakeFiles/pswitch.dir/src/share_func/network_transfer.c.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/share_func/network_transfer.c.s
.PHONY : src/share_func/network_transfer.c.s

src/share_func/repair.o: src/share_func/repair.c.o

.PHONY : src/share_func/repair.o

# target to build an object file
src/share_func/repair.c.o:
	$(MAKE) -f CMakeFiles/storagenodes.dir/build.make CMakeFiles/storagenodes.dir/src/share_func/repair.c.o
	$(MAKE) -f CMakeFiles/pswitch.dir/build.make CMakeFiles/pswitch.dir/src/share_func/repair.c.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/share_func/repair.c.o
.PHONY : src/share_func/repair.c.o

src/share_func/repair.i: src/share_func/repair.c.i

.PHONY : src/share_func/repair.i

# target to preprocess a source file
src/share_func/repair.c.i:
	$(MAKE) -f CMakeFiles/storagenodes.dir/build.make CMakeFiles/storagenodes.dir/src/share_func/repair.c.i
	$(MAKE) -f CMakeFiles/pswitch.dir/build.make CMakeFiles/pswitch.dir/src/share_func/repair.c.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/share_func/repair.c.i
.PHONY : src/share_func/repair.c.i

src/share_func/repair.s: src/share_func/repair.c.s

.PHONY : src/share_func/repair.s

# target to generate assembly for a file
src/share_func/repair.c.s:
	$(MAKE) -f CMakeFiles/storagenodes.dir/build.make CMakeFiles/storagenodes.dir/src/share_func/repair.c.s
	$(MAKE) -f CMakeFiles/pswitch.dir/build.make CMakeFiles/pswitch.dir/src/share_func/repair.c.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/share_func/repair.c.s
.PHONY : src/share_func/repair.c.s

src/share_func/share_func.o: src/share_func/share_func.c.o

.PHONY : src/share_func/share_func.o

# target to build an object file
src/share_func/share_func.c.o:
	$(MAKE) -f CMakeFiles/storagenodes.dir/build.make CMakeFiles/storagenodes.dir/src/share_func/share_func.c.o
	$(MAKE) -f CMakeFiles/pswitch.dir/build.make CMakeFiles/pswitch.dir/src/share_func/share_func.c.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/share_func/share_func.c.o
.PHONY : src/share_func/share_func.c.o

src/share_func/share_func.i: src/share_func/share_func.c.i

.PHONY : src/share_func/share_func.i

# target to preprocess a source file
src/share_func/share_func.c.i:
	$(MAKE) -f CMakeFiles/storagenodes.dir/build.make CMakeFiles/storagenodes.dir/src/share_func/share_func.c.i
	$(MAKE) -f CMakeFiles/pswitch.dir/build.make CMakeFiles/pswitch.dir/src/share_func/share_func.c.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/share_func/share_func.c.i
.PHONY : src/share_func/share_func.c.i

src/share_func/share_func.s: src/share_func/share_func.c.s

.PHONY : src/share_func/share_func.s

# target to generate assembly for a file
src/share_func/share_func.c.s:
	$(MAKE) -f CMakeFiles/storagenodes.dir/build.make CMakeFiles/storagenodes.dir/src/share_func/share_func.c.s
	$(MAKE) -f CMakeFiles/pswitch.dir/build.make CMakeFiles/pswitch.dir/src/share_func/share_func.c.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/share_func/share_func.c.s
.PHONY : src/share_func/share_func.c.s

src/storagenodes/storagenodes_main.o: src/storagenodes/storagenodes_main.c.o

.PHONY : src/storagenodes/storagenodes_main.o

# target to build an object file
src/storagenodes/storagenodes_main.c.o:
	$(MAKE) -f CMakeFiles/storagenodes.dir/build.make CMakeFiles/storagenodes.dir/src/storagenodes/storagenodes_main.c.o
.PHONY : src/storagenodes/storagenodes_main.c.o

src/storagenodes/storagenodes_main.i: src/storagenodes/storagenodes_main.c.i

.PHONY : src/storagenodes/storagenodes_main.i

# target to preprocess a source file
src/storagenodes/storagenodes_main.c.i:
	$(MAKE) -f CMakeFiles/storagenodes.dir/build.make CMakeFiles/storagenodes.dir/src/storagenodes/storagenodes_main.c.i
.PHONY : src/storagenodes/storagenodes_main.c.i

src/storagenodes/storagenodes_main.s: src/storagenodes/storagenodes_main.c.s

.PHONY : src/storagenodes/storagenodes_main.s

# target to generate assembly for a file
src/storagenodes/storagenodes_main.c.s:
	$(MAKE) -f CMakeFiles/storagenodes.dir/build.make CMakeFiles/storagenodes.dir/src/storagenodes/storagenodes_main.c.s
.PHONY : src/storagenodes/storagenodes_main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... storagenodes"
	@echo "... pswitch"
	@echo "... client"
	@echo "... src/client/client_main.o"
	@echo "... src/client/client_main.i"
	@echo "... src/client/client_main.s"
	@echo "... src/pswitch/pswitch_main.o"
	@echo "... src/pswitch/pswitch_main.i"
	@echo "... src/pswitch/pswitch_main.s"
	@echo "... src/share_func/bandwidth.o"
	@echo "... src/share_func/bandwidth.i"
	@echo "... src/share_func/bandwidth.s"
	@echo "... src/share_func/file_opt.o"
	@echo "... src/share_func/file_opt.i"
	@echo "... src/share_func/file_opt.s"
	@echo "... src/share_func/network_transfer.o"
	@echo "... src/share_func/network_transfer.i"
	@echo "... src/share_func/network_transfer.s"
	@echo "... src/share_func/repair.o"
	@echo "... src/share_func/repair.i"
	@echo "... src/share_func/repair.s"
	@echo "... src/share_func/share_func.o"
	@echo "... src/share_func/share_func.i"
	@echo "... src/share_func/share_func.s"
	@echo "... src/storagenodes/storagenodes_main.o"
	@echo "... src/storagenodes/storagenodes_main.i"
	@echo "... src/storagenodes/storagenodes_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

